### ISSUE TITLE
time-tracker: Send emails to admin and bizdev@opencurrents.com when user records hours for existing org and admin = "Someone else"

### ISSUE THREAD

**Issue by dannypernik** [opencurrents/opencurrents#748]

**Comment by nickolashe** [comment]
@MaxTattenbach @dannypernik you can this one a test now

**Comment by dannypernik** [comment]
@nickolashe looks like the default values are getting passed into the template instead of vars:
<img width="622" alt="screen shot 2017-12-09 at 12 13 10 pm" src="https://user-images.githubusercontent.com/3347095/33798228-7220f8c4-dcda-11e7-806c-7bcd0069105b.png">

Are you only wanting to test "Someone else" button? I also clicked the "Request Currents" button and tried submitting hours, but Admin field was required. Should I change admin select box to required=False? The one limitation of this would be how to throw an error if neither admin select nor admin text input are filled.
<img width="694" alt="screen shot 2017-12-09 at 12 16 10 pm" src="https://user-images.githubusercontent.com/3347095/33798271-1fe4dfd4-dcdb-11e7-9221-718fae40abce.png">

**Comment by MaxTattenbach** [comment]
@tevtonez

**Comment by MaxTattenbach** [comment]
@tevtonez  emails don't seem to be sending to neither the admin nor the bizdev@openCurrents.com

**Comment by tevtonez** [comment]
@MaxTattenbach I introduced a fix and created a PR.
Please, test it again once the fix is merged to develop, thanks!

**Comment by nickolashe** [comment]
this needs a retest from what i understand

**Comment by MaxTattenbach** [comment]
@tevtonez still not receiving email at bizdev nor admin when hours are being recorded under "someone else".

**Comment by MaxTattenbach** [comment]
@nickolashe it seems like #836 needs to be merged before we can give this a round of testing

**Comment by tevtonez** [comment]
@nickolashe @MaxTattenbach a fix has been pushed recently and tests passed. 
It can be re-tested after #836 PR is approved.

**Comment by MaxTattenbach** [comment]
@tevtonez thanks for heads up!

**Comment by nickolashe** [comment]
needs testing

**Comment by dannypernik** [comment]
@nickolashe @tevtonez Received this error when trying to submit form with "Someone else" selected:
![image](https://user-images.githubusercontent.com/3347095/34067484-bc965d42-e1ec-11e7-9d58-15d40c617d0c.png)

**Comment by tevtonez** [comment]
Great catch @dannypernik it should be fixed now. Pushed 2 fixes to kostya_time_tracker_update branch

**Comment by nickolashe** [comment]
@tevtonez do we have a unit test that tests this use case?

**Comment by nickolashe** [comment]
its on row 26 of oC MVP use case specs, Time tracker tab:
https://docs.google.com/spreadsheets/d/15mnrkl4Rc5dsFX8VAGOeuPPfCQTPHyOWV1SVwkXIqNQ/edit#gid=994160613&range=26:26

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez 
Note that new admin is unable to create his account after he receives email because the system says the account is already existent.
I noticed that new admin password is being created automatically when hours are submitted not sure if that's the problem.   

Tried to reset the password for new admin under "forgot my password" but rest password email didn't come through so I couldn't close the cycle. 

Currents are being created for the user and new admin org user is also being created.  That seems to be working fine. 

@dannypernik  please take a look at the flow of this link of the email sent to admin should direct him where he can directly create an account.  Also, ideally the messaging in the email template could include hours and description of work. 

![image](https://user-images.githubusercontent.com/26234440/34090423-75d75c8a-e37c-11e7-8cd5-e1b48f48d0da.png)

**Comment by tevtonez** [comment]
@MaxTattenbach 
I got the information that a new NPF admin account should be created without a password, if a volunteer logs time mentioning a non-registered admin.
Now I see that it's impossible to log in with empty password field.
Please, let me know, which password should we use as default?
Thanks!

**Comment by tevtonez** [comment]
@MaxTattenbach @nickolashe 
tests are added but marked for skipping due to issue with time tracking form (as per discussion with Max)

**Comment by nickolashe** [comment]
@dannypernik @MaxTattenbach @tevtonez to clarify things here a bit:
1. new admin is created without a password
2. hours are tracked under this account
3. it is correct that admin should not be able to log in just yet, otherwise anyone could log in to all new accounts
4. i think the main problem is the email sent to admin directs him to the homepage, whereas what we should really sending them a variation of the `verify-email` template, saying a volunteer added them and here is the link to confirm their account.

**Comment by MaxTattenbach** [comment]
@nickolashe I am in agreement with #4 above., if not it becomes too many steps.

**Comment by dannypernik** [comment]
@nickolashe the one issue with the suggestion to direct a new admin straight to verify-email is that he/she will not have a first/last name saved for the account. Don't we have it set up such that a user who has an account created with no password can still sign up through homepage and save first/last name, then get verification email directing to verify-email?

**Comment by nickolashe** [comment]
@dannypernik that is correct, yes. now what is the issue again?

**Comment by dannypernik** [comment]
@nickolashe - @MaxTattenbach suggested that it's too many steps to have an invited admin go to homepage from invite email, create an account, go back to email to verify account, and save password. I don't see a way around it assuming we want user to always have a name. Plus I think an invited admin should be directed to homepage so they know what they're signing up for.

**Comment by MaxTattenbach** [comment]
@dannypernik  I am ok with making them go to home for the mean time no biggie

**Comment by MaxTattenbach** [comment]
@tevtonez seems that we need to create user but not create a password for him. 
@nickolashe we should use the same as live dashboard where a user is created without a password

**Comment by MaxTattenbach** [comment]
@tevtonez emails are been sent correctly the only issue is creating the password for new admin.

**Comment by tevtonez** [comment]
@MaxTattenbach @nickolashe newly created NPF admin gets empty password here
https://github.com/opencurrents/opencurrents/blob/89a24d42e000e577e67b185d5e98e0fd3d8301f1/openCurrents/views.py#L1019
Am I missing something? Please, let me know, thanks!

**Comment by tevtonez** [comment]
@MaxTattenbach I talk to nickolashe and removed the line where we set the password, it'll be merged to develop soon.

**Comment by MaxTattenbach** [comment]
@maxtattenbach  connect Gala's account on the back end and see if Currents appear on her admin profile.

**Comment by dannypernik** [comment]
@dannypernik

**Comment by MaxTattenbach** [comment]
@dannypernik Thanks!

**Comment by MaxTattenbach** [comment]
@nickolashe @tevtonez   This is working going to close!
